### ISSUE TITLE
Discrepancy in instructions

### ISSUE THREAD

**Issue by Sushk1821** [CS5704-VT/Workshops#10]
@chbrown13 
It was mentioned to create a workshop repository in the assignment details on canvas, but a link was given in the slack to add our issues.
Please let me know if I misunderstood.

**Comment by chbrown13** [comment]
Yes, the assignment says to add an issue to the workshop repository (this one) _not_ the one you created for the tutorial

**Comment by chbrown13** [comment]
Wording can be updated to be made clearer

**Comment by Sushk1821** [comment]
Got It! Thank You, Professor
