### ISSUE TITLE
Navigating through the subsections for the workshop

### ISSUE THREAD

**Issue by sumukh23** [CS5704-VT/Workshops#11]
The basics workshop content is very informative, but I just had a slight confusion in navigating through the different subparts. It can be helpful if you can put the files names for each subsection in the Readme file. 
Eg. In the readme file for the programming languages subsection, you can link the Coding.md file with the title or mention the file name in the description. Thanks. 

@chbrown13

**Comment by chbrown13** [comment]
Got it, thanks
