### ISSUE TITLE
Interactive Bash Scripts

### ISSUE THREAD

**Issue by PratikNalage** [CS5704-VT/Workshops#12]
Hello, I was really looking forward to doing the workshop on Docable, but unfortunately, it's still having some NGINX server issues. Maybe in the future, we can have something like interactive bash scripts. So that even if the external sites like Docable go down, we can still run the scripts on our local machines. 
However, the major challenge with this would be to handle cross-platform compatibility among Windows, Unix, and Linux. We can address this issue via Cygwin which runs Linux-based commands in Windows.

**Comment by chbrown13** [comment]
Ok cool, thanks!
