### ISSUE TITLE
502 Bad Gateway with [Workshop] Engineering Basics

### ISSUE THREAD

**Issue by kbeaumont18** [CS5704-VT/Workshops#17]
Docable threw a 502 Bad Gateway exception. The site was working properly at the start of class, but started failing for everyone at the same time.

[proposed label] bug

![image](https://user-images.githubusercontent.com/70178609/150372757-1f960d8c-b79d-4897-bfff-3ad85308d015.png)

**Comment by chbrown13** [comment]
Thanks

**Comment by chbrown13** [comment]
Fixed with new version of Docable.
