### ISSUE TITLE
Facing issues with Docable

### ISSUE THREAD

**Issue by swanandsv** [CS5704-VT/Workshops#18]
Facing some issues with regards to Docable.

**Comment by chbrown13** [comment]
For next time, your issue should be more descriptive and report a specific issue

**Comment by swanandsv** [comment]
> For next time, your issue should be more descriptive and report a specific issue
Okay Professor got it. Will do from next time onwards.

**Comment by chbrown13** [comment]
Fixed with new version of Docable.
