### ISSUE TITLE
Encourage search to avoid duplication.

### ISSUE THREAD

**Issue by Disha2494** [CS5704-VT/Workshops#20]
[documentation]
Encourage reporters to search for existing issues before submitting new issues. This saves time for everyone.
Creating a document called CONTRIBUTING.md in the root of the repository can be used to describe the preferred issue reporting workflow, and emphasize the importance of searching for existing issues before submitting anything new.

When the repository has contributing guidelines in place, every time a new user tries to create their first issue, they see a prominent overlay with a link to contributor guidelines.

**Comment by chbrown13** [comment]
Good idea
