### ISSUE TITLE
Missing Title Instructions for README.md

### ISSUE THREAD

**Issue by ejones12** [CS5704-VT/Workshops#3]
In the Activity: Creating a Repo

We are asked to create a README.md file with basic information for the workshop. However, in class the professor demonstrated how to create a Title/Header for a README.md but these instructions were not in the workshop.

Solution:
Adding: 
`# CS5704 SE Basics Workshop`
to the top of my README.md file solved this issue. 

I think this is an important skill that should be added to the workshop for future lessons.

**Comment by chbrown13** [comment]
Thanks, will make the instructions clearer
