### ISSUE TITLE
Order of the Navigation Bar

### ISSUE THREAD

**Issue by recorder233** [CS5704-VT/Workshops#5]
![图片](https://user-images.githubusercontent.com/49328576/150467872-13709080-f9bf-4242-ae29-59b2c7148d24.png)
The order of tabs in the navigation bar is different from the actual order that the workshop proceeds, it is kind of confusing when trying to go back to the previous page

**Comment by chbrown13** [comment]
Good to know, thanks

**Comment by chbrown13** [comment]
Fixed with new version of Docable.
