### ISSUE TITLE
Broken link to Docable in README.md

### ISSUE THREAD

**Issue by ramapinnimty** [CS5704-VT/Workshops#6]
@chbrown13 The link to Docable under the Overview section in Basics/README.md is broken.

> This workshop provides a brief overview of several useful tools and activities for supporting software development work and skills to help you be productive as a software engineer.[^1] These interactive tutorials will be based on **Docable**, an ...

Kindly fix it by updating the link or highlighting the issue to the users. Thanks.

**Comment by chbrown13** [comment]
Cool, thanks
