### ISSUE TITLE
Broken links to images in file Basics/Git.md

### ISSUE THREAD

**Issue by elink9** [CS5704-VT/Workshops#8]
When clicking on the links to images in [Basics/Git.md](https://github.com/CS5704-VT/Workshops/blob/main/Basics/Git.md), the links lead to 404 errors. An image of the landing page for the 404 error is shown at the end of this issue. It looks like the below links reference blobs that are not present in the repository. 

Consider changing the links or adding the missing files to the repository with the requisite path to make the links work properly.

Shortcuts to the broken links are as follows (the text is linked to the broken link in the Git.md file):

> [git object model](https://github.com/CS5704-VT/Workshops/blob/bce04c7ffc2945ee059921e039386a525ff5ba08/Basics/Git.md?plain=1#L29)

> [img](https://github.com/CS5704-VT/Workshops/blob/bce04c7ffc2945ee059921e039386a525ff5ba08/Basics/Git.md?plain=1#L52)

>  [img](https://github.com/CS5704-VT/Workshops/blob/bce04c7ffc2945ee059921e039386a525ff5ba08/Basics/Git.md?plain=1#L64)

> [img](https://github.com/CS5704-VT/Workshops/blob/bce04c7ffc2945ee059921e039386a525ff5ba08/Basics/Git.md?plain=1#L71)

> [git commit](https://github.com/CS5704-VT/Workshops/blob/bce04c7ffc2945ee059921e039386a525ff5ba08/Basics/Git.md?plain=1#L85)

> [git-branches](https://github.com/CS5704-VT/Workshops/blob/bce04c7ffc2945ee059921e039386a525ff5ba08/Basics/Git.md?plain=1#L129)

> [git-staging](https://github.com/CS5704-VT/Workshops/blob/bce04c7ffc2945ee059921e039386a525ff5ba08/Basics/Git.md?plain=1#L208)

> [git-remote](https://github.com/CS5704-VT/Workshops/blob/bce04c7ffc2945ee059921e039386a525ff5ba08/Basics/Git.md?plain=1#L242)

Below is the 404 landing page for the links listed above when accessed from Git.md. 
![image](https://user-images.githubusercontent.com/32229168/150568679-68aa2dac-417a-4c6d-9295-83041c0f5f48.png)

**Comment by chbrown13** [comment]
Thanks!
